import { Flex, Heading, Image, Text } from "@chakra-ui/react";
import Head from "next/head";
import ReactTypingEffect from "react-typing-effect";
import { frases } from "../data/frases";
import { Header } from "../components/Header";
import { PoppoverInfo } from "../components/PoppoverInfo";
import { HeroSection } from "../components/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Delta UOU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column" minH="100vh" position="relative">
        <Header />

        <HeroSection />
      </Flex>
    </>
  );
}
